import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ReCaptchaProvider } from "next-recaptcha-v3";
import { DisableInspectRightClick } from "@/utils/disability";

const SpaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={`${SpaceGrotesk.className} antialiased select-none`}>
        <DisableInspectRightClick />
        {children}
      </body>
    </html>
  );
}
